### ISSUE TITLE
Add dynamic music for different jobs (and situations?)

### ISSUE THREAD

**Issue by Zangeiti** [butmun/Interpost-Hague#121]
Instead of having the same, static song for every character, how about adding different songs for different jobs? It'll help with the immersion of your character, i.e. cool badass military music for security/traitors(?)/whatever. Be sure to have each song play right after one ends **AND/OR** have players choose their own combat music for their characters.

Music: https://www.dropbox.com/s/uunt8pv1sl67cex/Interbay%20Music.zip?dl=0

**Comment by Muncher2112** [comment]
This is done, and easy to add to
