### ISSUE TITLE
Make the game download all the resources at once instead of every time you open a menu or see a new thing.

### ISSUE THREAD

**Issue by karmaisblackandbluepilled** [butmun/Interpost-Hague#150]
lifeweb does it and it helps prevent lag

**Comment by Muncher2112** [comment]
Do you know if there is a way to do this?  Like does another (opensource) server do it?

**Comment by karmaisblackandbluepilled** [comment]
I know that lifeweb makes you download a zip with all the resources that then gets put in the .rsc but nothing more

**Comment by karmaisblackandbluepilled** [comment]
@Muncher2112 CEV Eris apparently does it
