### ISSUE TITLE
Add a femur breaker

### ISSUE THREAD

**Issue by SireTurret** [butmun/Interpost-Hague#167]
I'm not kidding. It should be the arbiter's tool.

**Comment by Muncher2112** [comment]
Alternatively, pick from any of the torture devices from here

https://amnesia.fandom.com/wiki/Torture_Chambers

**Comment by SireTurret** [comment]
FEMUR BREAKER

**Comment by mrpibb4201337** [comment]
https://en.wikipedia.org/wiki/Foot_roasting
https://en.wikipedia.org/wiki/Thumbscrew_(torture)
https://en.wikipedia.org/wiki/Rat_torture
https://en.wikipedia.org/wiki/Chinese_water_torture
these are better
