### ISSUE TITLE
Re1Taz To-Do List

### ISSUE THREAD

**Issue by Re2Taz** [butmun/Interpost-Hague#190]
Hey Re1Tard. Remember to add this some day.

Add bow code. So you can knot arrows on it.

Add helmet sounds upon impact. The classic Interbay 1.0 "BUNK" sound.

Add starvation system so people can actually starve to death.

**Comment by Punkinguy** [comment]
we need starvation!!!!!!!

**Comment by SireTurret2** [comment]
Closing this.
