### ISSUE TITLE
make the combat system BETTER

### ISSUE THREAD

**Issue by SireTurret** [butmun/Interpost-Hague#34]
We need, no, we REQUIRE a better combat system with different combat styles, different martial arts, different dueling, different everything!

**Comment by Muncher2112** [comment]
![](https://i.gyazo.com/f14f1df82c86b23128c2acb56271af7d.png)

**Comment by SireTurret** [comment]
What's left:

snowflake procs scattered across the codebase

and uhh maybe a bit more work on functions?

**Comment by Muncher2112** [comment]
Hotkeys are the only other thing I can think of

**Comment by Muncher2112** [comment]
Add strength requirements to weapons (Based on item weight?).  Heavier items attack slower in fast mode and light weapons do less damage in strong mode.

**Comment by Muncher2112** [comment]
Add a "feint" mechanic, as a counter to defensive mode

**Comment by Muncher2112** [comment]
Make aim effect shooting (This is hard, because the bullet doesn't know who shot it when it tries to determine if it should hit or not)

**Comment by Muncher2112** [comment]
Commit 74332ee88d9ce8b458f1c87367ffa7c672c631d6 is part of this
