### ISSUE TITLE
16 errors 54 warnings

### ISSUE THREAD

**Issue by Muncher2112** [butmun/Interpost-Hague#5]
#### Description of issue

Lots of errors and warnings in vscode

![](https://i.gyazo.com/71c1922ead569e840c0c3367b1320bda.png)

I cri

#### Difference between expected and actual behavior

No errors or warnings

#### Steps to reproduce 

Open in vs code

Look into:

https://github.com/Muncher2112/Interbay/issues/22

https://github.com/Muncher2112/Interbay/commit/19d986a85820ff4df152d83fe95e4b5d6c59103d

https://github.com/Muncher2112/Interbay/commit/7ababc37a4d4ab13cbe82a477f9541f958491142

**Comment by SireTurret** [comment]
I am not sure if this is still relevant.
