### ISSUE TITLE
Improve and modularize how parrying works

### ISSUE THREAD

**Issue by Muncher2112** [butmun/Interpost-Hague#77]
Parrying is aids.  It's tied to shield stuff, which is a default thing for items, and it's not easy to write code for. 

Give it it's own functions, checks etc.  Basically untie it from shields

**Comment by Muncher2112** [comment]
I've figured out how to easily add parrying to items.   The question is, do we just keep sticking this special snowflake function onto random items (easy way) or do we refactor everything we want to parry into it's own type (harder way)

**Comment by Zangeiti** [comment]
parrying will have a huge impact in combat, i'd say go for the hard way
