### ISSUE TITLE
Add legcuffing

### ISSUE THREAD

**Issue by SireTurret** [butmun/Interpost-Hague#92]
To prevent people getting kicked in the head.

**Comment by Muncher2112** [comment]
https://github.com/Baystation12/Baystation12/commit/af99faf4a3dfe4088b31612b48ed8c21b183dd7d

**Comment by SireTurret** [comment]
I forgot I added these. Oops

**Comment by SireTurret** [comment]
The only problem is making them not be able to kick people, though. Also add them on the map.
