### ISSUE TITLE
Add the Dreamer from lifeweb

### ISSUE THREAD

**Issue by karmaisblackandbluepilled** [butmun/Interpost-Hague#94]
Dreamer's an antag with high stats, maximum melee and ranged skill whose purpose is to kill people, make statues out of their gibs, make people view the statues and extract the numbers in their hearts to make a sum of them, put them into his diary and wake up from the simulation that is this world.

DO IT.

**Comment by SireTurret** [comment]
This will require EXTENSIVE coding. We also could add in some of our own ideas.

**Comment by miner99213** [comment]
No. Not with Frontier at least, since it is small, it is really antag - sided. We are having trouble with a sneks, imagine snek on a steroids and with ranged in close quarters and straight corridors of frontier. It is fucking mess.
